// <auto-generated />
using System;
using LinkConverter.Repository.EFPostgresql.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LinkConverter.Repository.EFPostgresql.Migrations
{
    [DbContext(typeof(LinkConverterContext))]
    partial class LinkConverterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LinkConverter.Domain.DBEntity.LinkConverterHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte>("ConvertType")
                        .HasColumnName("CONVERT_TYPE")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestLink")
                        .IsRequired()
                        .HasColumnName("REQUEST_LINK")
                        .HasColumnType("text");

                    b.Property<string>("ResponseLink")
                        .IsRequired()
                        .HasColumnName("RESPONSE_LINK")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LINKCONVERT_HISTORIES");
                });
#pragma warning restore 612, 618
        }
    }
}
